QuizWebApplication/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizWebApplication.Models.Dto;
using QuizWebApplication.Services;

namespace QuizWebApplication.Controllers
{
    [Authorize(Policy = "RequireAdministratorRole")]
    public class AdminController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        private readonly IAdminService _adminService;
        public AdminController(ICategoryService categoryService, IMapper mapper, IAdminService adminService)
        {
            _categoryService = categoryService;
            _mapper = mapper;
            _adminService = adminService;
        }
       
       public IActionResult Management()
       {
            return View();
       }

       public IActionResult GetCategories()
       {
            var categories = _categoryService.GetAll();
            return View(categories);
       }

       public IActionResult CreateCategory()
       {
            return View();
       }

       [HttpPost]
       public IActionResult CreateCategory(CategoryDto dto)
       {
            _adminService.CreateCategory(dto);
            return View();
       }
       
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null)
                return NotFound();

            var category = _categoryService.GetById(id);

            return View(category);
        }

       [HttpPost]
       public IActionResult DeleteCategoryPost(int? id)
       {
            if(id == null || id==0)
            {
                return NotFound();
            }
            return RedirectToAction("GetCategories");


       }

        public IActionResult CreateQuestion(CategoryDto dto)
        {
            var categoryId = dto.Id;
            TempData["id"] = categoryId;

            return View();
        }

        [HttpPost]
        public IActionResult CreateQuestionPost(QuestionDto dto)
        {
            var id = Convert.ToInt32(TempData["id"]);

            _adminService.CreateQuestion(dto, id);


            return RedirectToAction("CreateQuestion");
        }

    }
}

QuizWebApplication/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizWebApplication.Models.Dto;
using QuizWebApplication.Services;

namespace QuizWebApplication.Controllers
{
    [AllowAnonymous]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        //return view with data 
        
        public IActionResult CategoryMainView()
        {
            var category = _categoryService.GetAll();

            return View(category);
        }


        public IActionResult DescriptionCategoryView(CategoryDto categoryDto)
        {

            return View(categoryDto);
        }
    }
}

QuizWebApplication/Controllers/RankingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizWebApplication.Data;
using QuizWebApplication.Models;

namespace QuizWebApplication.Controllers
{
    [AllowAnonymous]
    public class RankingController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public RankingController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult GetRanking()
        {
            var ranking = _dbContext.Rankings.ToList();

            List<Ranking> SortedList = ranking.OrderByDescending(o => o.Points).ToList();


            return View(SortedList);
        }
        


    }
}

QuizWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuizWebApplication.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
       <div class="sidenav">
              <a asp-action="Index" asp-controller="Home">Home</a>
              <a asp-action="CategoryMainView" asp-controller="Category">Play</a>
              <a asp-action="GetRanking" asp-controller="Ranking">Ranking</a>
              <a href="#">Contact</a>
              <a asp-action="Management" asp-controller="Admin">Admin Panel</a>
              <partial name="_LoginPartial" />
            </div>
    </header>
   
    <div class="main">
            @RenderBody()
    </div>
       
 @*   <partial name="_LoginPartial" />*@

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="_framework/blazor.server.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>