QuizWebApplication/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QuizWebApplication.Models
{
    public class Category
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public List<Question> Questions { get; set; }
    }
}

QuizWebApplication/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizWebApplication.Models.Dto;
using QuizWebApplication.Services;

namespace QuizWebApplication.Controllers
{
    [AllowAnonymous]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        //return view with data 
        
        public IActionResult CategoryMainView()
        {
            var category = _categoryService.GetAll();

            return View(category);
        }


        public IActionResult DescriptionCategoryView(CategoryDto categoryDto)
        {

            return View(categoryDto);
        }
    }
}

QuizWebApplication/Controllers/QuestionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuizWebApplication.Data;
using QuizWebApplication.Models;
using QuizWebApplication.Models.Dto;
using QuizWebApplication.Services;

namespace QuizWebApplication.Controllers
{
    [AllowAnonymous]
    public class QuestionController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IMapper _mapper;
        private readonly IQuestionService _service;
        private readonly IRankingService _rankService;
        private readonly UserManager<IdentityUser> _userManager;
        public QuestionController(ApplicationDbContext applicationDbContext, IMapper mapper,
            IQuestionService questionService, IRankingService rankService, UserManager<IdentityUser> userManager)
        {
            _dbContext = applicationDbContext;
            _mapper = mapper;
            _service = questionService;
            _rankService = rankService;
            _userManager = userManager;
        }
       



        public IActionResult QuestionView(CategoryDto dto)
        {

           var questionDto =  _service.GetQuestions(dto);

            return View(questionDto);
        }

        [HttpPost]
        public IActionResult QuestionView(IFormCollection formCollection) // 0 i parzyste indeksy to pytania
        {
            var points = _service.SetAnswers(formCollection);

            return RedirectToAction("PointsView", new { points = points });
        }

        [AllowAnonymous]
        public async Task<IActionResult> PointsView(int points)
        {
            var model = new Pointer();
            model.Points = points;

            const int maxPoints = 2;

            var user = await _userManager.GetUserAsync(HttpContext.User);

            if(user != null)
            {
                _rankService.AddPoints(user.UserName, points,maxPoints);
            }

            return View(model);
        }
        
    }
}

QuizWebApplication/Views/Category/CategoryMainView.cshtml
@model IEnumerable<QuizWebApplication.Models.Dto.CategoryDto>

@{
    ViewData["Title"] = "CategoryMainView";
}


 <link rel="stylesheet" href="~/css/CategoryMainView.css" asp-append-version="true" />

<div>

    <div class="text-center">
        <div>
           <h1 class="cat-title">Choose Category!</h1>

       
        </div>

    </div>

    <div class="mt-2">
        <div class="row mt-5">
       

                @foreach(var category in Model)
                {
                    var imagePath = "/quizPhotos/" + (category.Name + ".png");

                    <div class="col-4 mb-5 categories">
  
                            <a class="getCategory" asp-controller="Category" asp-action="DescriptionCategoryView" 
                            asp-route-Id="@category.Id"  asp-route-Name ="@category.Name">
                             
                              @category.Name
                            </a>     
                            <br/>
                   
                   
                    </div>
                }
        
        </div>
    </div>

    
    
</div>
@section Scripts{

<script>
    
var button = document.getElementById('button');

function SetRole() {

}


</script>
}

QuizWebApplication/Views/Category/DescriptionCategoryView.cshtml
@model QuizWebApplication.Models.Dto.CategoryDto
@{
    ViewData["Title"] = "Description";
}

<div class="container">

    
 

    <div class="categoryName">
        <h1>@Model.Name</h1>

    </div>
    <div class="description">
        <h3>@Model.Description</h3>

        <div> Please select option</div>
    </div>

    <div class="navigation">

        <a class="btn alert-danger"asp-controller="Category" asp-action="CategoryMainView"> Go back</a>
        <a class="btn alert-info"  asp-controller="Question" asp-action="QuestionView" asp-route-Id ="@Model.Id"> Let's go</a>
    </div>

</div>